/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElButton: typeof import('element-plus/es').ElButton
  const ElDatePickerCell: typeof import('element-plus/es').ElDatePickerCell
  const ElForm: typeof import('element-plus/es').ElForm
  const ElFormItem: typeof import('element-plus/es').ElFormItem
  const ElIcon: typeof import('element-plus/es').ElIcon
  const ElInput: typeof import('element-plus/es').ElInput
  const ElOption: typeof import('element-plus/es').ElOption
  const ElOptions: typeof import('element-plus/es').ElOptions
  const ElPopper: typeof import('element-plus/es').ElPopper
  const ElPopperArrow: typeof import('element-plus/es').ElPopperArrow
  const ElPopperContent: typeof import('element-plus/es').ElPopperContent
  const ElScrollbar: typeof import('element-plus/es').ElScrollbar
  const ElTag: typeof import('element-plus/es').ElTag
  const ElTeleport: typeof import('element-plus/es').ElTeleport
  const ElTooltip: typeof import('element-plus/es').ElTooltip
  const ElTooltipContent: typeof import('element-plus/es').ElTooltipContent
  const ElTooltipTrigger: typeof import('element-plus/es').ElTooltipTrigger
}
